=== Syric420/ComplementReseau/Serveur_FlightsManagement/build/classes/Test/listeVols.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/vols_prevus_poubelle-air_000214.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE listeVols SYSTEM "vols_prevus_poubelle-air_000214.dtd">

    <listeVols>
    ...
    </listeVols>
-->

<!ELEMENT listeVols (compagnie|createDestination|createFlights)*>

<!ELEMENT compagnie (nom|pays)*>
<!ATTLIST compagnie
    lowcost CDATA #IMPLIED
  >

<!ELEMENT nom (#PCDATA)>

<!ELEMENT pays (#PCDATA)>

<!ELEMENT createDestination (ville|pays)*>

<!ELEMENT ville (#PCDATA)>
<!ATTLIST ville
    zoneFranche CDATA #IMPLIED
  >
<!ELEMENT createFlights (vol)*>
<!ATTLIST createFlights
    destination CDATA #IMPLIED
    country CDATA #IMPLIED
  >
<!ELEMENT vol (date|time|prix)*>
<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT prix (#PCDATA)>

=== Syric420/ComplementReseau/Serveur_FlightsManagement/src/Test/vols_prevus_poubelle-air_000214.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Document : listeVols.xml
 Created on : 11/04/2018, 2:42PM
 Author : Vince
 Description: Purpose of the document follows.
-->
<!DOCTYPE listeVols SYSTEM "listeVols.dtd">

<listeVols>
    <compagnie lowcost="Y">
        <nom>Poubelle-air</nom>
        <pays>Boursoulavie</pays>
    </compagnie>
    <createDestination>
        <ville zoneFranche="T"> Saint-Hélier</ville>
        <pays>Jersey</pays>
    </createDestination>
    <createFlights>
        <vol>
            <date>27/12/2017</date>
            <time>8:30</time>
            <prix>225.30</prix>
        </vol>
        <vol>
            <date>27/12/2017</date>
            <time>14:30</time>
            <prix>185.75</prix>
        </vol>
        <vol>
            <date>30/12/2017</date>
            <time>8:30</time>
            <prix>225.30</prix>
        </vol>
    </createFlights>
    <createDestination>
        <ville zoneFranche="F">Aurillac</ville>
        <pays>France</pays>
    </createDestination>
    <createFlights>
        <vol>
        <date>27/12/2017</date> 
        <time>10:30</time>
        <prix>98.00</prix>
        </vol>
    </createFlights>
    <createFlights destination="Honolulu" country="Hawaï">
        <vol>
            <date>28/12/2017</date>
            <time>5:15</time>
            <prix>652.35</prix>
        </vol>
    </createFlights>
</listeVols>
